import { NextResponse } from "next/server";

// Mock data representing realistic search volumes across US metros
// TODO: Replace with actual Google Keyword Planner API integration

const mockMarketData = [
  {
    metro: "Phoenix",
    state: "AZ",
    monthly_searches: 8900,
    pontis_customers: 0,
    crm_companies: 14,
    opportunity_score: 89,
    trend: "up" as const,
    trend_pct: 12,
    top_keywords: ["headstones near me", "custom headstones", "grave markers"],
  },
  {
    metro: "Houston",
    state: "TX",
    monthly_searches: 12400,
    pontis_customers: 2,
    crm_companies: 23,
    opportunity_score: 84,
    trend: "up" as const,
    trend_pct: 8,
    top_keywords: ["grave markers", "cemetery monuments", "headstone engraving"],
  },
  {
    metro: "Miami",
    state: "FL",
    monthly_searches: 6200,
    pontis_customers: 0,
    crm_companies: 9,
    opportunity_score: 76,
    trend: "flat" as const,
    trend_pct: 2,
    top_keywords: ["memorial plaques", "headstones near me", "custom memorials"],
  },
  {
    metro: "Atlanta",
    state: "GA",
    monthly_searches: 7100,
    pontis_customers: 1,
    crm_companies: 18,
    opportunity_score: 71,
    trend: "up" as const,
    trend_pct: 15,
    top_keywords: ["headstones near me", "grave markers", "monument company"],
  },
  {
    metro: "Dallas",
    state: "TX",
    monthly_searches: 9200,
    pontis_customers: 1,
    crm_companies: 21,
    opportunity_score: 78,
    trend: "up" as const,
    trend_pct: 6,
    top_keywords: ["grave markers", "headstone engraving", "cemetery monuments"],
  },
  {
    metro: "Las Vegas",
    state: "NV",
    monthly_searches: 3400,
    pontis_customers: 0,
    crm_companies: 7,
    opportunity_score: 64,
    trend: "up" as const,
    trend_pct: 9,
    top_keywords: ["headstones near me", "custom grave markers", "memorial stones"],
  },
  {
    metro: "Los Angeles",
    state: "CA",
    monthly_searches: 18600,
    pontis_customers: 3,
    crm_companies: 42,
    opportunity_score: 82,
    trend: "flat" as const,
    trend_pct: 1,
    top_keywords: ["memorial plaques", "custom headstones", "grave markers"],
  },
  {
    metro: "San Diego",
    state: "CA",
    monthly_searches: 4800,
    pontis_customers: 1,
    crm_companies: 11,
    opportunity_score: 58,
    trend: "down" as const,
    trend_pct: 3,
    top_keywords: ["memorial plaques", "headstones near me", "cremation memorials"],
  },
  {
    metro: "Denver",
    state: "CO",
    monthly_searches: 5200,
    pontis_customers: 2,
    crm_companies: 13,
    opportunity_score: 52,
    trend: "up" as const,
    trend_pct: 7,
    top_keywords: ["headstones near me", "mountain memorial stones", "grave markers"],
  },
  {
    metro: "Salt Lake City",
    state: "UT",
    monthly_searches: 720,
    pontis_customers: 3,
    crm_companies: 8,
    opportunity_score: 22,
    trend: "flat" as const,
    trend_pct: 0,
    top_keywords: ["headstones near me", "custom headstones", "memorial plaques"],
  },
  {
    metro: "Portland",
    state: "OR",
    monthly_searches: 4100,
    pontis_customers: 0,
    crm_companies: 9,
    opportunity_score: 67,
    trend: "up" as const,
    trend_pct: 11,
    top_keywords: ["eco-friendly memorials", "headstones near me", "grave markers"],
  },
  {
    metro: "Seattle",
    state: "WA",
    monthly_searches: 6800,
    pontis_customers: 1,
    crm_companies: 15,
    opportunity_score: 69,
    trend: "up" as const,
    trend_pct: 5,
    top_keywords: ["headstones near me", "custom memorials", "cremation stones"],
  },
  {
    metro: "Chicago",
    state: "IL",
    monthly_searches: 11200,
    pontis_customers: 2,
    crm_companies: 28,
    opportunity_score: 74,
    trend: "flat" as const,
    trend_pct: 2,
    top_keywords: ["grave markers", "headstones near me", "cemetery monuments"],
  },
  {
    metro: "New York City",
    state: "NY",
    monthly_searches: 15800,
    pontis_customers: 4,
    crm_companies: 38,
    opportunity_score: 71,
    trend: "down" as const,
    trend_pct: 4,
    top_keywords: ["memorial plaques", "headstones near me", "urban cemeteries"],
  },
  {
    metro: "Boston",
    state: "MA",
    monthly_searches: 5600,
    pontis_customers: 1,
    crm_companies: 12,
    opportunity_score: 61,
    trend: "up" as const,
    trend_pct: 4,
    top_keywords: ["headstones near me", "historic grave markers", "memorial stones"],
  },
  {
    metro: "Philadelphia",
    state: "PA",
    monthly_searches: 7400,
    pontis_customers: 2,
    crm_companies: 16,
    opportunity_score: 63,
    trend: "flat" as const,
    trend_pct: 1,
    top_keywords: ["grave markers", "headstones near me", "cemetery monuments"],
  },
  {
    metro: "Tampa",
    state: "FL",
    monthly_searches: 4900,
    pontis_customers: 0,
    crm_companies: 11,
    opportunity_score: 72,
    trend: "up" as const,
    trend_pct: 14,
    top_keywords: ["memorial plaques", "headstones near me", "coastal memorials"],
  },
  {
    metro: "Charlotte",
    state: "NC",
    monthly_searches: 3800,
    pontis_customers: 0,
    crm_companies: 8,
    opportunity_score: 68,
    trend: "up" as const,
    trend_pct: 18,
    top_keywords: ["headstones near me", "grave markers", "custom memorials"],
  },
  {
    metro: "Austin",
    state: "TX",
    monthly_searches: 4200,
    pontis_customers: 1,
    crm_companies: 9,
    opportunity_score: 57,
    trend: "up" as const,
    trend_pct: 13,
    top_keywords: ["grave markers", "custom headstones", "memorial stones"],
  },
  {
    metro: "San Antonio",
    state: "TX",
    monthly_searches: 5100,
    pontis_customers: 0,
    crm_companies: 12,
    opportunity_score: 73,
    trend: "up" as const,
    trend_pct: 9,
    top_keywords: ["grave markers", "cemetery monuments", "headstones near me"],
  },
  {
    metro: "Nashville",
    state: "TN",
    monthly_searches: 3600,
    pontis_customers: 0,
    crm_companies: 7,
    opportunity_score: 66,
    trend: "up" as const,
    trend_pct: 16,
    top_keywords: ["headstones near me", "custom grave markers", "memorial stones"],
  },
  {
    metro: "Indianapolis",
    state: "IN",
    monthly_searches: 3200,
    pontis_customers: 1,
    crm_companies: 9,
    opportunity_score: 48,
    trend: "flat" as const,
    trend_pct: 0,
    top_keywords: ["grave markers", "headstones near me", "monument company"],
  },
  {
    metro: "Columbus",
    state: "OH",
    monthly_searches: 3900,
    pontis_customers: 1,
    crm_companies: 10,
    opportunity_score: 54,
    trend: "up" as const,
    trend_pct: 6,
    top_keywords: ["headstones near me", "grave markers", "cemetery monuments"],
  },
  {
    metro: "Minneapolis",
    state: "MN",
    monthly_searches: 4400,
    pontis_customers: 0,
    crm_companies: 10,
    opportunity_score: 70,
    trend: "up" as const,
    trend_pct: 8,
    top_keywords: ["headstones near me", "winter-proof memorials", "grave markers"],
  },
  {
    metro: "Detroit",
    state: "MI",
    monthly_searches: 5800,
    pontis_customers: 1,
    crm_companies: 14,
    opportunity_score: 65,
    trend: "flat" as const,
    trend_pct: 2,
    top_keywords: ["grave markers", "headstones near me", "memorial stones"],
  },
];

const mockKeywordData = [
  { region: "Southwest (AZ, NV, NM)", keyword: "headstones near me", volume: 34000, trend: "up" as const, trend_pct: 12 },
  { region: "Northeast (NY, MA, PA)", keyword: "grave markers", volume: 28000, trend: "flat" as const, trend_pct: 0 },
  { region: "South (TX, GA, FL)", keyword: "cemetery monuments", volume: 19000, trend: "up" as const, trend_pct: 8 },
  { region: "California", keyword: "memorial plaques", volume: 22000, trend: "down" as const, trend_pct: 3 },
  { region: "Pacific Northwest (WA, OR)", keyword: "eco-friendly memorials", volume: 8400, trend: "up" as const, trend_pct: 22 },
  { region: "Midwest (IL, OH, MI)", keyword: "grave markers", volume: 16500, trend: "flat" as const, trend_pct: 1 },
  { region: "Mountain West (CO, UT)", keyword: "headstones near me", volume: 7200, trend: "up" as const, trend_pct: 7 },
  { region: "Southeast (NC, TN, GA)", keyword: "custom headstones", volume: 14800, trend: "up" as const, trend_pct: 16 },
];

export async function GET() {
  try {
    // Sort by opportunity score descending
    const sortedMarkets = [...mockMarketData].sort((a, b) => b.opportunity_score - a.opportunity_score);

    return NextResponse.json({
      markets: sortedMarkets,
      keywords: mockKeywordData,
      last_updated: "2026-03-03T09:00:00Z",
      data_source: "mock_data", // Will change to "google_keyword_planner" when API is integrated
    });
  } catch (error) {
    console.error("Error fetching market intelligence:", error);
    return NextResponse.json(
      { error: "Failed to fetch market intelligence data" },
      { status: 500 }
    );
  }
}
